# Generated by Django 3.2.6 on 2023-02-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementitem',
            name='atmosphericPressure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='measurementitem',
            name='brightness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
